"""create initial schema

Revision ID: a63a55a2b864
Revises: 
Create Date: 2026-07-21 12:16:25.877009
"""
from alembic import op
import sqlalchemy as sa

revision = 'a63a55a2b864'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('average_service_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_bank_id'), 'branches', ['bank_id'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PAUSED', 'CLOSED', name='queue_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_branch_id'), 'staff', ['branch_id'], unique=False)
    op.create_table('queue_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('queue_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'READY', 'CHECKED_IN', 'SERVING', 'COMPLETED', 'SKIPPED', 'CANCELLED', name='queue_entry_status'), nullable=False),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id', 'queue_number', name='uq_queue_entries_queue_number')
    )
    op.create_table('queue_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_entry_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('JOINED', 'READY', 'CHECKED_IN', 'CALLED', 'SERVICE_STARTED', 'SERVICE_COMPLETED', 'SKIPPED', 'CANCELLED', name='queue_event_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_events_queue_entry_id'), 'queue_events', ['queue_entry_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_events_queue_entry_id'), table_name='queue_events')
    op.drop_table('queue_events')
    op.drop_table('queue_entries')
    op.drop_index(op.f('ix_staff_branch_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_table('queues')
    op.drop_index(op.f('ix_branches_bank_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('banks')
    # ### end Alembic commands ###
